// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CopyImageToWorkspace(arg1, arg2) {
  return window['go']['main']['App']['CopyImageToWorkspace'](arg1, arg2);
}

export function ListDirectory(arg1) {
  return window['go']['main']['App']['ListDirectory'](arg1);
}

export function OpenFile() {
  return window['go']['main']['App']['OpenFile']();
}

export function ReadFile(arg1) {
  return window['go']['main']['App']['ReadFile'](arg1);
}

export function ReadImageBase64(arg1) {
  return window['go']['main']['App']['ReadImageBase64'](arg1);
}

export function SaveFile(arg1, arg2) {
  return window['go']['main']['App']['SaveFile'](arg1, arg2);
}

export function SaveImage(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveImage'](arg1, arg2, arg3);
}
