// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function OpenFile():Promise<Record<string, string>>;

export function ReadFile(arg1:string):Promise<Record<string, string>>;

export function SaveFile(arg1:string,arg2:string):Promise<string>;
